# Generated by Django 4.0.2 on 2022-10-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(max_length=1000)),
                ('github', models.URLField(max_length=1000)),
                ('twitter', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('short_bio', models.CharField(max_length=100, null=True)),
                ('long_bio', models.TextField(null=True)),
                ('advocate_years_exp', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('company', models.ManyToManyField(to='api.Company')),
                ('social_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.socialmedialinks')),
            ],
        ),
    ]
