# Generated by Django 4.0.2 on 2022-10-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='social_links',
        ),
        migrations.DeleteModel(
            name='SocialMediaLinks',
        ),
    ]
