# Generated by Django 4.0.2 on 2022-10-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_advocate_social_links_delete_socialmedialinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(max_length=1000)),
                ('github', models.URLField(max_length=1000)),
                ('twitter', models.URLField(max_length=1000)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advocate')),
            ],
        ),
    ]
